### ISSUE TITLE
CUDA out of memory with Multiple GPUs

### ISSUE THREAD

**Issue by axi345** [cornellius-gp/gpytorch#1448]
I run a program with gpytorch that needed more than 30GB GPU memory, so I decide to run it with multiple GPUs.

```
class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, x_train, y_train, likelihood, num_tasks):
        super(MultitaskGPModel, self).__init__(x_train, y_train, likelihood)
        self.mean_module = gpytorch.means.MultitaskMean(gpytorch.means.ConstantMean(), num_tasks=num_tasks)
        self.covar_module = MultitaskKernel(RBFKernel(), num_tasks=num_tasks, rank=1)
        if torch.cuda.device_count() > 1:
            self.covar_module = MultiDeviceKernel(base_kernel=self.covar_module,
                                                  device_ids=range(torch.cuda.device_count()))

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)
```

But when I use the following code to train the model, it still uses less than 30GB GPU memory, which is the memory of a single GPU.

```
def fit(x_train, y_train, epoch=0, lr=0.1):
    x_train = torch.from_numpy(x_train).float().cuda()
    y_train = torch.from_numpy(y_train).float().cuda()
    likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=y_train.shape[1]).cuda()
    model = MultitaskGPModel(x_train, y_train, likelihood, y_train.shape[1]).cuda()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
    for i in range(epoch):
        optimizer.zero_grad()
        output = model(x_train)
        loss = -mll(output, y_train)
        loss.backward()
        optimizer.step()
```
So the error occurs:

`RuntimeError: CUDA out of memory. Tried to allocate 15.01 GiB (GPU 0; 31.75 GiB total capacity; 15.01 GiB already allocated; 913.75 MiB free; 29.65 GiB reserved in total by PyTorch)`

I want to know how to make use of  the memory of multiple GPUs, because my dataset is relatively large, so this problem is very important to me.

**Comment by gpleiss** [comment]
The multi-gpu code isn't well tested for multitask models. Any chance you can put up a full code example?
For the time being, it might be better to use a multi-output SVGP model, which will scale better with dataset size.

**Comment by NicPy4** [comment]
I have kind of the same issue regarding the MultiDeviceKernel(). I copied the example from 'Exact GP Regression with Multiple GPUs and Kernel Partitioning' just with my data (~100.000 samples and one input feature). I have 8 GPUs with each one having 32GB, but still the program only tries to allocate on one GPU.

        x_train = torch.Tensor(x_train)
        y_train = torch.Tensor(y_train)
        x_test = torch.Tensor(x_test)
        y_test = torch.Tensor(y_test)
        x_train, y_train = x_train.contiguous(), y_train.contiguous()
        x_test, y_test = x_test.contiguous(), y_test.contiguous()
        output_device = torch.device('cuda:0')
        train_x, train_y = x_train.to(output_device), y_train.to(output_device)
        test_x, test_y = x_test.to(output_device), y_test.to(output_device)
        n_devices = torch.cuda.device_count()
        print('Planning to run on {} GPUs.'.format(n_devices))
        print(n_devices)

        class ExactGPModel(gpytorch.models.ExactGP):
            def __init__(self, train_x, train_y, likelihood, n_devices):
                super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
                self.mean_module = gpytorch.means.ConstantMean()
                base_covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

                self.covar_module = gpytorch.kernels.MultiDeviceKernel(
                    base_covar_module, device_ids=range(n_devices),
                    output_device=output_device
                )

            def forward(self, x):
                mean_x = self.mean_module(x)
                covar_x = self.covar_module(x)
                return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

        def train(train_x,
                  train_y,
                  n_devices,
                  output_device,
                  checkpoint_size,
                  preconditioner_size,
                  n_training_iter,
                  ):
            likelihood = gpytorch.likelihoods.GaussianLikelihood().to(output_device)
            model = ExactGPModel(train_x, train_y, likelihood, n_devices).to(output_device)
            model.train()
            likelihood.train()

            optimizer = FullBatchLBFGS(model.parameters(), lr=0.1)
            # "Loss" for GPs - the marginal log likelihood
            mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

            with gpytorch.beta_features.checkpoint_kernel(checkpoint_size), \
                    gpytorch.settings.max_preconditioner_size(preconditioner_size):

                def closure():
                    optimizer.zero_grad()
                    output = model(train_x)
                    loss = -mll(output, train_y)
                    return loss

                loss = closure()
                loss.backward()

                for i in range(n_training_iter):
                    options = {'closure': closure, 'current_loss': loss, 'max_ls': 10}
                    loss, _, _, _, _, _, _, fail = optimizer.step(options)

                    print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
                        i + 1, n_training_iter, loss.item(),
                        model.covar_module.module.base_kernel.lengthscale.item(),
                        model.likelihood.noise.item()
                    ))

                    if fail:
                        print('Convergence reached!')
                        break

            print(f"Finished training on {train_x.size(0)} data points using {n_devices} GPUs.")
            return model, likelihood

        def find_best_gpu_setting(train_x,
                                  train_y,
                                  n_devices,
                                  output_device,
                                  preconditioner_size
                                  ):
            N = train_x.size(0)

            # Find the optimum partition/checkpoint size by decreasing in powers of 2
            # Start with no partitioning (size = 0)
            settings = [0] + [int(n) for n in np.ceil(N / 2 ** np.arange(1, np.floor(np.log2(N))))]

            for checkpoint_size in settings:
                print('Number of devices: {} -- Kernel partition size: {}'.format(n_devices, checkpoint_size))
                try:
                    # Try a full forward and backward pass with this setting to check memory usage
                    _, _ = train(train_x, train_y,
                                 n_devices=n_devices, output_device=output_device,
                                 checkpoint_size=checkpoint_size,
                                 preconditioner_size=preconditioner_size, n_training_iter=1)

                    # when successful, break out of for-loop and jump to finally block
                    break
                except RuntimeError as e:
                    print('RuntimeError: {}'.format(e))
                except AttributeError as e:
                    print('AttributeError: {}'.format(e))
                finally:
                    # handle CUDA OOM error
                    gc.collect()
                    torch.cuda.empty_cache()
            return checkpoint_size

        # Set a large enough preconditioner size to reduce the number of CG iterations run
        preconditioner_size = 100
        checkpoint_size = find_best_gpu_setting(train_x, train_y,
                                                n_devices=n_devices,
                                                output_device=output_device,
                                                preconditioner_size=preconditioner_size)

        model, likelihood = train(train_x, train_y,
                                  n_devices=n_devices, output_device=output_device,
                                  checkpoint_size=10000,
                                  preconditioner_size=100,
                                  n_training_iter=20)

The output/error I get is this:

    Number of devices: 8 -- Kernel partition size: 43413
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 21707
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 10854
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 5427
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 2714
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 1357
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 679
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 340
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 170
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 85
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 43
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 22
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 11
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 6
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Number of devices: 8 -- Kernel partition size: 3
    RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I don't really get where my error is since I just copied the provided code. 

Thanks for the help!

**Comment by tangw-ml** [comment]
> I have kind of the same issue regarding the MultiDeviceKernel(). I copied the example from 'Exact GP Regression with Multiple GPUs and Kernel Partitioning' just with my data (~100.000 samples and one input feature). I have 8 GPUs with each one having 32GB, but still the program only tries to allocate on one GPU.
> 
> ```
>     x_train = torch.Tensor(x_train)
>     y_train = torch.Tensor(y_train)
>     x_test = torch.Tensor(x_test)
>     y_test = torch.Tensor(y_test)
>     x_train, y_train = x_train.contiguous(), y_train.contiguous()
>     x_test, y_test = x_test.contiguous(), y_test.contiguous()
>     output_device = torch.device('cuda:0')
>     train_x, train_y = x_train.to(output_device), y_train.to(output_device)
>     test_x, test_y = x_test.to(output_device), y_test.to(output_device)
>     n_devices = torch.cuda.device_count()
>     print('Planning to run on {} GPUs.'.format(n_devices))
>     print(n_devices)
> 
>     class ExactGPModel(gpytorch.models.ExactGP):
>         def __init__(self, train_x, train_y, likelihood, n_devices):
>             super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
>             self.mean_module = gpytorch.means.ConstantMean()
>             base_covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
> 
>             self.covar_module = gpytorch.kernels.MultiDeviceKernel(
>                 base_covar_module, device_ids=range(n_devices),
>                 output_device=output_device
>             )
> 
>         def forward(self, x):
>             mean_x = self.mean_module(x)
>             covar_x = self.covar_module(x)
>             return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
> 
>     def train(train_x,
>               train_y,
>               n_devices,
>               output_device,
>               checkpoint_size,
>               preconditioner_size,
>               n_training_iter,
>               ):
>         likelihood = gpytorch.likelihoods.GaussianLikelihood().to(output_device)
>         model = ExactGPModel(train_x, train_y, likelihood, n_devices).to(output_device)
>         model.train()
>         likelihood.train()
> 
>         optimizer = FullBatchLBFGS(model.parameters(), lr=0.1)
>         # "Loss" for GPs - the marginal log likelihood
>         mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
> 
>         with gpytorch.beta_features.checkpoint_kernel(checkpoint_size), \
>                 gpytorch.settings.max_preconditioner_size(preconditioner_size):
> 
>             def closure():
>                 optimizer.zero_grad()
>                 output = model(train_x)
>                 loss = -mll(output, train_y)
>                 return loss
> 
>             loss = closure()
>             loss.backward()
> 
>             for i in range(n_training_iter):
>                 options = {'closure': closure, 'current_loss': loss, 'max_ls': 10}
>                 loss, _, _, _, _, _, _, fail = optimizer.step(options)
> 
>                 print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
>                     i + 1, n_training_iter, loss.item(),
>                     model.covar_module.module.base_kernel.lengthscale.item(),
>                     model.likelihood.noise.item()
>                 ))
> 
>                 if fail:
>                     print('Convergence reached!')
>                     break
> 
>         print(f"Finished training on {train_x.size(0)} data points using {n_devices} GPUs.")
>         return model, likelihood
> 
>     def find_best_gpu_setting(train_x,
>                               train_y,
>                               n_devices,
>                               output_device,
>                               preconditioner_size
>                               ):
>         N = train_x.size(0)
> 
>         # Find the optimum partition/checkpoint size by decreasing in powers of 2
>         # Start with no partitioning (size = 0)
>         settings = [0] + [int(n) for n in np.ceil(N / 2 ** np.arange(1, np.floor(np.log2(N))))]
> 
>         for checkpoint_size in settings:
>             print('Number of devices: {} -- Kernel partition size: {}'.format(n_devices, checkpoint_size))
>             try:
>                 # Try a full forward and backward pass with this setting to check memory usage
>                 _, _ = train(train_x, train_y,
>                              n_devices=n_devices, output_device=output_device,
>                              checkpoint_size=checkpoint_size,
>                              preconditioner_size=preconditioner_size, n_training_iter=1)
> 
>                 # when successful, break out of for-loop and jump to finally block
>                 break
>             except RuntimeError as e:
>                 print('RuntimeError: {}'.format(e))
>             except AttributeError as e:
>                 print('AttributeError: {}'.format(e))
>             finally:
>                 # handle CUDA OOM error
>                 gc.collect()
>                 torch.cuda.empty_cache()
>         return checkpoint_size
> 
>     # Set a large enough preconditioner size to reduce the number of CG iterations run
>     preconditioner_size = 100
>     checkpoint_size = find_best_gpu_setting(train_x, train_y,
>                                             n_devices=n_devices,
>                                             output_device=output_device,
>                                             preconditioner_size=preconditioner_size)
> 
>     model, likelihood = train(train_x, train_y,
>                               n_devices=n_devices, output_device=output_device,
>                               checkpoint_size=10000,
>                               preconditioner_size=100,
>                               n_training_iter=20)
> ```
> 
> The output/error I get is this:
> 
> ```
> Number of devices: 8 -- Kernel partition size: 43413
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 21707
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 10854
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 5427
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 2714
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 1357
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 679
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 340
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 170
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 85
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 43
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 22
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 11
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 6
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Number of devices: 8 -- Kernel partition size: 3
> RuntimeError: CUDA out of memory. Tried to allocate 28.09 GiB (GPU 0; 31.75 GiB total capacity; 28.08 GiB already allocated; 3.22 GiB free; 28.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```
> 
> I don't really get where my error is since I just copied the provided code.
> 
> Thanks for the help!

Hello. I had the same problem. Have you found a solution?

**Comment by tangw-ml** [comment]
Hello. I had the same problem. Have you found a solution? @NicPy4

**Comment by NicPy4** [comment]
@tangw-ml Hei, unfortunately not. I decided to use a different approach now using KISS GP and Stochastic Variational GP Regression. So I can handle my large data set without running into out-of-memory error messages.

**Comment by gpleiss** [comment]
@NicPy4 @tangw-ml try using KeOps kernels on a single GPU - it is far more memory efficient (and much faster) than using the MultiDeviceKernel.

See https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html

**Comment by NicPy4** [comment]
@gpleiss Hey thanks for your help! I tried KeOps and it works for me.

I have one question regarding KeOps and extrapolation. I used SpectralMixtureKernel for my extrapolation with SVGP which works quite good. Can I use it for KeOps as well? Or do you have a recommendation for me on what I could use? I use the GPs in my thesis for Predictive Maintenance to forecast engine behavior.

Thank u!

**Comment by gpleiss** [comment]
@NicPy4 we don't have a KeOps spectral mixture kernel, but it shouldn't be too difficult to write one yourself, once https://github.com/cornellius-gp/linear_operator/pull/62 is merged into the LinearOperator repo. (see https://github.com/cornellius-gp/gpytorch/blob/8a20024e09e924f5f239bb5070d35b1d95a56c1f/gpytorch/kernels/keops/periodic_kernel.py for inspiration).

I'm stretched very thin at the moment, so if you'd be up for writing a spectral mixture keeps kernel and putting up a PR that'd be great. (Wait until https://github.com/cornellius-gp/linear_operator/pull/62 is merged in tho.)

**Comment by NicPy4** [comment]
@gpleiss Okay then I will try this and will probably come back to you to ask for help when I'm done. 
I have due on my thesis next week so probably I'll implement it after that. 

Thanks for your help so far.

**Comment by gpleiss** [comment]
@NicPy4 as of the latest release (v1.11), https://github.com/cornellius-gp/linear_operator/pull/62 is merged in, so the keops spectral mixture kernel can be written.

Closing because checkpointing is now deprecated (as of v1.11)
