### ISSUE TITLE
[Bug] ExactGP training on GPU fails when dataset is too large

### ISSUE THREAD

**Issue by V-Xing** [cornellius-gp/gpytorch#2286]
# 🐛 Bug

When training an `ExactGP` with a KeOps RBF kernel on GPU, backpropagation fails if the size of the dataset exceeds a specific number.

## To reproduce

This is a basic training iteration. On my machine, this code fails when `n>=524266` and works when `n<524266`.
```python
import gpytorch
import torch

assert torch.cuda.is_available()
device = "cuda:0"

n = 524266
train_x = torch.randn([n, 1], device=device)
train_y = torch.randn(n, device=device)


class KeopsRBFModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(KeopsRBFModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.keops.RBFKernel(ard_num_dims=1)
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


likelihood = gpytorch.likelihoods.GaussianLikelihood().cuda()
model = KeopsRBFModel(train_x, train_y, likelihood).cuda()

model.train()
likelihood.train()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

optimizer.zero_grad()
output = model(train_x)
loss = -mll(output, train_y)
loss.backward()
optimizer.step()
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/home/xing/repos/surf/local-tests/reproducing_example.py", line 38, in <module>
    loss.backward()
  File "/home/xing/venvs/surf/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/xing/venvs/surf/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasStrsmBatched( handle, side, uplo, trans, diag, m, n, alpha, A, lda, B, ldb, batchCount)`
```

## Expected Behavior

With a smaller dataset, I do not have this error message.

I think this is very close to [this PyTorch issue](https://github.com/pytorch/pytorch/issues/79191) which is unfortunately still open. The root cause seems to be in the way CUDA handles large triangular solves. I can reproduce the error from this issue's minimal reproducing example on my end.

Two things are different compared to that issue:

- The CUDA error message is not the same: `CUBLAS_STATUS_NOT_SUPPORTED` for me, `CUBLAS_STATUS_EXECUTION_FAILED` for them.
- I don't get the error message at quite the same number of samples as them: `n=524266` vs. `n=524281`. This may be due to other parameters in Gpytorch that I'm not accounting for.

## System information

**Please complete the following information:**
- Gpytorch version: 1.9.1
- PyTorch version: '1.13.1+cu117'
- OS version: Ubuntu 20.04.5 LTS (x86_64)

## Additional context
Is there a way to bypass this issue? Something like using batches of size smaller than the one that crashes training?

If I'm not mistaken, exact GPs have been trained with Gpytorch on larger datasets than this (for instance in the Exact Gaussian Processes on a Million Data Points paper)?

**Comment by gpleiss** [comment]
I unfortunately don't think this is a GPyTorch issue - it probably is an error in KeOps or PyTorch, or it might be specific to your GPU or CUDA installation.

Sorry there's nothing that we can do :/

**Comment by Felice27** [comment]
Thank you for your process!  Loading the data in batches also worked for me, but I will also look into the SVGP and why it is the default process for data loaded in batches.
